import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:kattrick/models/models.dart' hide Notification;
import 'package:kattrick/models/notification.dart' as app_models;
import 'package:kattrick/data/repositories.dart';
import 'package:kattrick/data/repositories_providers.dart';
import 'package:kattrick/widgets/optimized_image.dart';

/// Non-member hub view - shows hub info for users who are not members
class HubNonMemberView extends ConsumerStatefulWidget {
  final Hub hub;
  final String hubId;
  final VenuesRepository venuesRepo;
  final UsersRepository usersRepo;
  final bool joinRequestsEnabled;

  const HubNonMemberView({
    super.key,
    required this.hub,
    required this.hubId,
    required this.venuesRepo,
    required this.usersRepo,
    required this.joinRequestsEnabled,
  });

  @override
  ConsumerState<HubNonMemberView> createState() => _HubNonMemberViewState();
}

class _HubNonMemberViewState extends ConsumerState<HubNonMemberView> {
  final TextEditingController _messageController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _messageController.dispose();
    super.dispose();
  }

  Future<void> _showJoinRequestDialog(BuildContext context) async {
    final messageController = TextEditingController();

    final result = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text('בקשת הצטרפות ל-${widget.hub.name}'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: messageController,
              maxLines: 3,
              decoration: const InputDecoration(
                hintText: 'הוסף הודעה למנהל ההאב... (אופציונלי)',
                border: OutlineInputBorder(),
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('ביטול'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text('שלח בקשה'),
          ),
        ],
      ),
    );

    if (result == true) {
      _messageController.text = messageController.text;
      await _sendJoinRequest();
    }

    messageController.dispose();
  }

  Future<void> _sendJoinRequest() async {
    final currentUserId = ref.read(currentUserIdProvider);
    if (currentUserId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('נא להתחבר')),
      );
      return;
    }

    final message = _messageController.text.trim();

    setState(() {
      _isSubmitting = true;
    });

    try {
      final notificationsRepo = ref.read(notificationsRepositoryProvider);
      final usersRepo = ref.read(usersRepositoryProvider);
      final firestore = FirebaseFirestore.instance;

      // Get current user for notification
      final requestingUser = await usersRepo.getUser(currentUserId);
      if (requestingUser == null) {
        throw Exception('לא ניתן למצוא את פרטי המשתמש');
      }

      // Get hub manager (creator)
      final managerId = widget.hub.createdBy;

      // 1. Save join request to Firestore: hubs/{hubId}/requests/{userId}
      await firestore
          .collection('hubs')
          .doc(widget.hubId)
          .collection('requests')
          .doc(currentUserId)
          .set({
        'userId': currentUserId,
        'hubId': widget.hubId,
        'message': message.isNotEmpty ? message : null,
        'status': 'pending',
        'createdAt': FieldValue.serverTimestamp(),
        'userName': requestingUser.name,
        'userPhotoUrl': requestingUser.photoUrl,
      });

      // 2. Create notification for hub manager
      final notification = app_models.Notification(
        notificationId: '', // Will be generated by createNotification
        userId: managerId,
        type: 'join_request',
        title: 'בקשת הצטרפות ל-${widget.hub.name}',
        body: message.isNotEmpty
            ? '${requestingUser.name} מבקש להצטרף: $message'
            : '${requestingUser.name} מבקש להצטרף להאב',
        read: false,
        createdAt: DateTime.now(),
        data: {
          'hubId': widget.hubId,
          'requestingUserId': currentUserId,
          'requestId': currentUserId, // Use userId as requestId
        },
      );

      await notificationsRepo.createNotification(notification);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('הבקשה להצטרפות נשלחה למנהל ההאב'),
            backgroundColor: Colors.green,
          ),
        );
        // Clear message field
        _messageController.clear();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('שגיאה בשליחת הבקשה: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final venuesStream = widget.venuesRepo.watchVenuesByHub(widget.hubId);
    final showManagerContact =
        widget.hub.settings['showManagerContactInfo'] as bool? ?? true;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Hub profile image
          Center(
            child: widget.hub.profileImageUrl != null
                ? OptimizedImage(
                    imageUrl: widget.hub.profileImageUrl ?? '',
                    width: 150,
                    height: 150,
                    fit: BoxFit.cover,
                    borderRadius: BorderRadius.circular(16),
                    errorWidget: Container(
                      width: 150,
                      height: 150,
                      decoration: BoxDecoration(
                        color: Colors.grey[300],
                        borderRadius: BorderRadius.circular(16),
                      ),
                      child: const Icon(Icons.group, size: 80),
                    ),
                  )
                : Container(
                    width: 150,
                    height: 150,
                    decoration: BoxDecoration(
                      color: Colors.grey[300],
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: const Icon(Icons.group, size: 80),
                  ),
          ),
          const SizedBox(height: 24),

          // Hub name
          Center(
            child: Text(
              widget.hub.name,
              style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
              textAlign: TextAlign.center,
            ),
          ),
          const SizedBox(height: 16),

          // Number of participants
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                children: [
                  Icon(
                    Icons.group,
                    size: 24,
                    color: Theme.of(context).colorScheme.primary,
                  ),
                  const SizedBox(width: 12),
                  Text(
                    '${widget.hub.memberCount} משתתפים',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Description
          if (widget.hub.description != null &&
              widget.hub.description!.isNotEmpty) ...[
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Text(
                  widget.hub.description ?? '',
                  style: Theme.of(context).textTheme.bodyMedium,
                ),
              ),
            ),
            const SizedBox(height: 16),
          ],

          // Contact Manager button
          if (showManagerContact) ...[
            _ContactManagerButton(
              hub: widget.hub,
              usersRepo: widget.usersRepo,
            ),
            const SizedBox(height: 16),
          ],

          // Venues list
          Card(
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'מגרשים',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                  const SizedBox(height: 12),
                  StreamBuilder<List<Venue>>(
                    stream: venuesStream,
                    builder: (context, snapshot) {
                      if (snapshot.connectionState == ConnectionState.waiting) {
                        return const Center(child: CircularProgressIndicator());
                      }

                      final venues = snapshot.data ?? [];
                      if (venues.isEmpty) {
                        return Text(
                          'אין מגרשים רשומים',
                          style:
                              Theme.of(context).textTheme.bodySmall?.copyWith(
                                    color: Colors.grey[600],
                                  ),
                        );
                      }

                      return Column(
                        children: venues.map((venue) {
                          return Padding(
                            padding: const EdgeInsets.only(bottom: 12),
                            child: Row(
                              children: [
                                Icon(
                                  Icons.location_on,
                                  size: 20,
                                  color: Theme.of(context).colorScheme.primary,
                                ),
                                const SizedBox(width: 8),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        venue.name,
                                        style: Theme.of(context)
                                            .textTheme
                                            .bodyMedium
                                            ?.copyWith(
                                              fontWeight: FontWeight.w500,
                                            ),
                                      ),
                                      if (venue.address != null &&
                                          venue.address!.isNotEmpty)
                                        Text(
                                          venue.address ?? '',
                                          style: Theme.of(context)
                                              .textTheme
                                              .bodySmall
                                              ?.copyWith(
                                                color: Colors.grey[600],
                                              ),
                                        ),
                                    ],
                                  ),
                                ),
                              ],
                            ),
                          );
                        }).toList(),
                      );
                    },
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 24),

          // Join request section
          if (widget.joinRequestsEnabled) ...[
            // If hub is private, show "Request to Join" button that opens a dialog
            if (widget.hub.isPrivate) ...[
              SizedBox(
                width: double.infinity,
                child: ElevatedButton.icon(
                  onPressed: _isSubmitting
                      ? null
                      : () => _showJoinRequestDialog(context),
                  icon: _isSubmitting
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Icon(Icons.person_add),
                  label: Text(_isSubmitting ? 'שולח...' : 'בקש להצטרף'),
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                ),
              ),
            ] else ...[
              // If hub is not private, show the full form
              Card(
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'הודעה (אופציונלי)',
                        style: Theme.of(context).textTheme.titleSmall,
                      ),
                      const SizedBox(height: 8),
                      TextField(
                        controller: _messageController,
                        maxLines: 3,
                        decoration: const InputDecoration(
                          hintText: 'כתוב הודעה למנהל ההאב...',
                          border: OutlineInputBorder(),
                        ),
                      ),
                      const SizedBox(height: 16),
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          onPressed: _isSubmitting ? null : _sendJoinRequest,
                          icon: _isSubmitting
                              ? const SizedBox(
                                  width: 20,
                                  height: 20,
                                  child:
                                      CircularProgressIndicator(strokeWidth: 2),
                                )
                              : const Icon(Icons.send),
                          label: Text(
                              _isSubmitting ? 'שולח...' : 'שלח בקשת הצטרפות'),
                          style: ElevatedButton.styleFrom(
                            padding: const EdgeInsets.symmetric(vertical: 16),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ] else ...[
            Card(
              color: Colors.grey[200],
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Row(
                  children: [
                    Icon(
                      Icons.lock,
                      color: Colors.grey[700],
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Text(
                        'האב סגור',
                        style:
                            Theme.of(context).textTheme.titleMedium?.copyWith(
                                  color: Colors.grey[700],
                                ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }
}

/// Contact Manager button widget
class _ContactManagerButton extends ConsumerWidget {
  final Hub hub;
  final UsersRepository usersRepo;

  const _ContactManagerButton({
    required this.hub,
    required this.usersRepo,
  });

  Future<void> _contactManager(BuildContext context) async {
    try {
      // Get manager user (hub creator)
      final manager = await usersRepo.getUser(hub.createdBy);
      if (manager == null) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('לא ניתן למצוא את מנהל ההאב')),
          );
        }
        return;
      }

      if (!context.mounted) return;
      // Show dialog with contact options
      final contactMethod = await showDialog<String>(
        context: context,
        builder: (context) => AlertDialog(
          title: Text('צור קשר עם ${manager.name}'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              if (manager.phoneNumber != null &&
                  manager.phoneNumber!.isNotEmpty)
                ListTile(
                  leading: const Icon(Icons.phone, color: Colors.green),
                  title: const Text('WhatsApp'),
                  subtitle: Text(manager.phoneNumber!),
                  onTap: () => Navigator.pop(context, 'whatsapp'),
                ),
              if (manager.email.isNotEmpty)
                ListTile(
                  leading: const Icon(Icons.email, color: Colors.blue),
                  title: const Text('אימייל'),
                  subtitle: Text(manager.email),
                  onTap: () => Navigator.pop(context, 'email'),
                ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('ביטול'),
            ),
          ],
        ),
      );

      if (contactMethod == null) return;

      if (contactMethod == 'whatsapp' && manager.phoneNumber != null) {
        // Open WhatsApp
        final phone = manager.phoneNumber!.replaceAll(RegExp(r'[-\s]'), '');
        final url = Uri.parse('https://wa.me/$phone');
        if (await canLaunchUrl(url)) {
          await launchUrl(url, mode: LaunchMode.externalApplication);
        } else {
          if (context.mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('לא ניתן לפתוח WhatsApp')),
            );
          }
        }
      } else if (contactMethod == 'email') {
        // Open email
        final url = Uri.parse(
            'mailto:${manager.email}?subject=בקשה להצטרפות ל-${hub.name}');
        if (await canLaunchUrl(url)) {
          await launchUrl(url, mode: LaunchMode.externalApplication);
        } else {
          if (context.mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('לא ניתן לפתוח אפליקציית אימייל')),
            );
          }
        }
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('שגיאה: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'צור קשר עם מנהל ההאב',
              style: Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton.icon(
                onPressed: () => _contactManager(context),
                icon: const Icon(Icons.contact_support),
                label: const Text('צור קשר'),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 16),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
