// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzet6M6R3ZjTUyrmCCu2h6FhHeIUTyaGM',
    appId: '1:731836758075:web:449fbf8f2f634a2f03441e',
    messagingSenderId: '731836758075',
    projectId: 'kickabout-ddc06',
    authDomain: 'kickabout-ddc06.firebaseapp.com',
    storageBucket: 'kickabout-ddc06.firebasestorage.app',
    measurementId: 'G-BKSMX7BJ59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzz0lNtzpqFPcZalk3OIxjdsSuq-F8dFI',
    appId: '1:731836758075:android:0dde0fad28e8c51003441e',
    messagingSenderId: '731836758075',
    projectId: 'kickabout-ddc06',
    storageBucket: 'kickabout-ddc06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA50hudmE3ifuRuQvYT1WaSTE_mYA72SuU',
    appId: '1:731836758075:ios:652bbc8c7695854403441e',
    messagingSenderId: '731836758075',
    projectId: 'kickabout-ddc06',
    storageBucket: 'kickabout-ddc06.firebasestorage.app',
    androidClientId: '731836758075-d9maq17n6a05a38l4uc6c70vt36bml7b.apps.googleusercontent.com',
    iosClientId: '731836758075-qa8aofinufoogggaijcjr3kn3h2mln5j.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}